#!/bin/bash

rm -rf doc
mkdir doc
javadoc ../src/ru/ifmo/ctddev/berezhko/iterativeparallelism/IterativeParallelism.java -classpath "../../../java-advanced-2015/artifacts/IterativeParallelismTest.jar" -d doc -private -linkoffline http://docs.oracle.com/javase/8/docs/api/ http://docs.oracle.com/javase/8/docs/api/
