#!/bin/bash

java -cp ".:../../../java-advanced-2015/artifacts/ImplementorTest.jar:../../../java-advanced-2015/lib/hamcrest-core-1.3.jar:../../../java-advanced-2015/lib/junit-4.11.jar:../../../java-advanced-2015/lib/quickcheck-0.6.jar:../out/production/3th" info.kgeorgiy.java.advanced.implementor.Tester interface ru.ifmo.ctddev.berezhko.implementor.Implementor $1
