#!/bin/bash

java -cp ".:ImplementorTest.jar:hamcrest-core-1.3.jar:junit-4.11.jar:quickcheck-0.6.jar:out/production/3th" info.kgeorgiy.java.advanced.implementor.Tester interface ru.ifmo.ctddev.berezhko.implementor.Implementor $1
