#!/bin/bash
rm -rf bin
mkdir bin
cp out/production/3th/ru bin -r
cp META-INF/ bin -r
cp ImplementorTest.jar bin -r
cp hamcrest-core-1.3.jar bin -r
cp junit-4.11.jar bin -r
cp quickcheck-0.6.jar bin -r
cd bin
jar cfm Implementor.jar META-INF/MANIFEST.MF ru
